import{a as p,S,i as d}from"./assets/vendor-BjmtRwYh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();function f({page:t,per_page:r,q:a}){return p.defaults.baseURL="https://pixabay.com/api/",p.get("",{params:{key:"45177061-dd77212e3ebf23708a837f031",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}}).then(({data:e})=>e)}function m(t){const r=new S(".gallery-list a",{captions:!0,captionsData:"alt",captionDelay:250}),a=document.querySelector(".gallery-list"),i=t.map(({webformatURL:e,largeImageURL:s,tags:l,likes:v,views:q,comments:x,downloads:P})=>`<li class="card-item scrol">
<a class="gallery-link"  href=${s}>
<img class="gallery-image"
src=${e} alt=${l} /></a>
   <div class="card-body">
     <p class="card-text">likes<span class="card-value"> ${v}</span></p>
     <p class="card-text">views<span class="card-value"> ${q}</span></p>
     <p class="card-text">comments<span class="card-value"> ${x}</span></p>
     <p class="card-text">downloads<span class="card-value"> ${P}</span></p>
</li>`).join("");a.insertAdjacentHTML("beforeend",i),r.refresh()}const w=document.querySelector(".search-form"),h=document.querySelector(".gallery-list"),n=document.querySelector(".loader"),c=document.querySelector(".btn-primary"),o={q:"",page:1,per_page:15,maxPage:0};function u(){c.classList.add("is-hidden")}function M(){c.classList.remove("is-hidden")}function g(){c.disabled=!0}function y(){c.disabled=!1}w.addEventListener("submit",$);u();async function $(t){t.preventDefault(),h.innerHTML="",n.classList.remove("hidden");const r=t.currentTarget;if(o.q=r.elements.query.value.trim(),o.q===""){d.error({position:"topRight",message:"Please fill the input"}),r.reset(),n.classList.add("hidden"),u();return}o.page=1,g();try{const{total:a,hits:i}=await f(o);if(o.maxPage=Math.ceil(a/o.per_page),m(i),o.maxPage>1?(M(),y(),c.addEventListener("click",b)):u(),i.length===0){d.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),n.classList.add("hidden");return}}catch(a){L(a)}finally{r.reset(),n.classList.add("hidden")}}function L(t){h.innerHTML="",d.error({position:"topRight",message:`${t}`})}async function b(){o.page+=1,g(),n.classList.remove("hidden");try{const t=await f(o);m(t.hits);const a=document.querySelector(".scrol").getBoundingClientRect();window.scrollBy({top:a.height*2,behavior:"smooth"})}catch(t){L(t)}finally{n.classList.add("hidden"),o.page===o.maxPage?(u(),d.info({message:"You have reached the end of search results.",position:"topRight",messageColor:"#ffffff",backgroundColor:"#4e75ff"}),c.removeEventListener("click",b)):y()}}
//# sourceMappingURL=commonHelpers.js.map
